// Generated by CoffeeScript 1.10.0
(function() {
  var fill;

  fill = function(container, liguid) {
    if (liguid == null) {
      liguid = "coffee";
    }
    "Filling the " + container + " with " + liquid;
    return module.exports = fill;
  };

}).call(this);
